
import "./globals.css";
import Footer from "@/components/Shared/Footer/Footer";
import SmoothScroll from "@/components/SmoothScroll/SmoothScroll";




export const metadata = {
  title: "Fit Track",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
