import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Shared/Footer/Footer";
import Nav from "@/components/Shared/Nav/Nav";
import SmoothScroll from "@/components/SmoothScroll/SmoothScroll";
import AuthProvider from "@/components/Authentication/AuthProvider/AuthProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fit Track",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Nav />
          <AuthProvider>
          {children}
          </AuthProvider>
          <Footer />
      </body>
    </html>
  );
}
